apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-with-volume-snapshot
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  # Persistent storage configuration
  storage:
    storageClass: csi-hostpath-sc
    size: 1Gi
  walStorage:
    storageClass: csi-hostpath-sc
    size: 1Gi

  tablespaces:
    - name: atablespace
      storage:
        size: 1Gi
        storageClass: csi-hostpath-sc
      temporary: false
    - name: another_tablespace
      storage:
        size: 2Gi
        storageClass: csi-hostpath-sc
      temporary: true
    - name: tablespacea1
      storage:
        size: 2Gi
        storageClass: csi-hostpath-sc

  # Backup properties
  backup:
    volumeGroupSnapshot:
       className: csi-hostpath-groupsnapclass
